spring:
  datasource:
    url: jdbc:mysql://localhost:3306/house
    username: root
    password: 990310
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/config.xml
#  type-aliases-package: com.liujin.entity
pagehelper:
  helper-dialect: mysql
server:
  servlet:
    context-path: /house
  port: 9090
#需要打印sql语句 所以加上了这段
logging:
  level:
    com:
      liujin:
        mapper: debug

